// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI588SLVib_jbGkF2sqEY28Ndn7OXvdhY',
    appId: '1:362421971371:web:02bd5d3c7aeffecfe90aee',
    messagingSenderId: '362421971371',
    projectId: 'kabotr-ccb9a',
    authDomain: 'kabotr-ccb9a.firebaseapp.com',
    storageBucket: 'kabotr-ccb9a.appspot.com',
    measurementId: 'G-38171RK9CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQB6li1S8nKEwOvZjG6Zs65WbYzWw68xE',
    appId: '1:362421971371:android:2e30568f412e7c26e90aee',
    messagingSenderId: '362421971371',
    projectId: 'kabotr-ccb9a',
    storageBucket: 'kabotr-ccb9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAvQZ-UdFBt0htrM6hg9oFO5yMbP_FUiY',
    appId: '1:362421971371:ios:07d7d45a114439b4e90aee',
    messagingSenderId: '362421971371',
    projectId: 'kabotr-ccb9a',
    storageBucket: 'kabotr-ccb9a.appspot.com',
    iosBundleId: 'com.example.kabotr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAvQZ-UdFBt0htrM6hg9oFO5yMbP_FUiY',
    appId: '1:362421971371:ios:f8791cf69e11a501e90aee',
    messagingSenderId: '362421971371',
    projectId: 'kabotr-ccb9a',
    storageBucket: 'kabotr-ccb9a.appspot.com',
    iosBundleId: 'com.example.kabotr.RunnerTests',
  );
}
